# Generated by Django 4.1.1 on 2022-10-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_teacher_mobile_no_alter_teacher_qulification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='address',
            new_name='skills',
        ),
    ]
