# Generated by Django 4.1.1 on 2022-10-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_teacher_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile_no',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qulification',
        ),
    ]
