# Generated by Django 4.1.1 on 2022-10-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_teacher_profile_img_alter_courserating_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='detail',
        ),
    ]
