# Generated by Django 4.1.1 on 2022-10-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_teacher_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profile_imgs/'),
        ),
    ]
