# Generated by Django 4.1.1 on 2022-10-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_teacher_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='qulification',
            new_name='qualification',
        ),
    ]
