# Generated by Django 4.1.1 on 2022-10-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_studentfavoritecourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '8.  Courses Rating'},
        ),
    ]
