# Generated by Django 4.1.1 on 2022-10-15 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_studentassignemt'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignemt',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
