# Generated by Django 4.1.1 on 2022-10-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_text', models.TextField()),
                ('notif_for', models.CharField(max_length=300)),
                ('notif_created_time', models.DateTimeField(auto_now_add=True)),
                ('notifiread_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '10. Notification ',
            },
        ),
    ]
