# Generated by Django 4.1.1 on 2022-10-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_quiz_quizquestion_coursequiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='ans4',
            field=models.CharField(default=False, max_length=300),
        ),
    ]
