# Generated by Django 4.1.1 on 2022-10-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_attempquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempquiz',
            name='right_ans',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
