# Generated by Django 4.1.1 on 2022-10-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_attempquiz_right_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempquiz',
            name='right_ans',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
