# Generated by Django 4.1.1 on 2022-10-24 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_studymaterial_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': '04. Chapters'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '03. Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '02.Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '08.  Courses Rating'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '05.Students'},
        ),
        migrations.AlterModelOptions(
            name='studentassignemt',
            options={'verbose_name_plural': '09.  Student Assignment '},
        ),
        migrations.AlterModelOptions(
            name='studentcourseenrollment',
            options={'verbose_name_plural': '06. Enrolled Courses'},
        ),
        migrations.AlterModelOptions(
            name='studentfavoritecourse',
            options={'verbose_name_plural': '07. Student  Favorite Courses'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '01.Teachers'},
        ),
    ]
