# Generated by Django 4.1.1 on 2022-10-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_chapter_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_view',
            field=models.BigIntegerField(default=0),
        ),
    ]
